# Generated by Django 3.1.7 on 2022-11-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdOffer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='offer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
