# Generated by Django 3.1.7 on 2022-11-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdOffer', '0002_auto_20221127_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
